### ISSUE TITLE
搭建白盒代码审计平台cobra-报了错误

### ISSUE THREAD

**Issue by whitetoday** [wufeifei/cobra#259]
我在搭建白盒代码审计平台cobra，根据安装文档提示在centos6.5的环境下 安装所有依赖环境都成功了！
但是在执行 python cobra.py install   (python版本是2.6 ) 的时候报过错，请问是什么原因？

下面是错误代码
`
Traceback (most recent call last):
  File "cobra.py", line 15, in <module>
    from app import web, manager
  File "/root/download/cobra/app/__init__.py", line 305, in <module>
    from app.controller import api
  File "/root/download/cobra/app/controller/api.py", line 22, in <module>
    from engine import scan
  File "/root/download/cobra/engine/scan.py", line 25, in <module>
    log.Log()
  File "/root/download/cobra/utils/log.py", line 26, in __init__
    logging.config.dictConfig({
AttributeError: 'module' object has no attribute 'dictConfig'
`

**Comment by wufeifei** [comment]
dictConfig 是python 2.7的特性
