### ISSUE TITLE
初始化数据库表结构和数据有问题

### ISSUE THREAD

**Issue by qq-tianqi** [wufeifei/cobra#45]
初始化数据库表结构和数据
   python cobra.py install
无法操作？谢谢！

**Comment by wufeifei** [comment]
重新更新最新的v1.4代码，再尝试下。
如果还有问题请贴下完整的截图。

**Comment by lianfeng30** [comment]
MAC
python cobra.py install
Traceback (most recent call last):
  File "cobra.py", line 14, in <module>
    from app import web, manager
  File "/Users/x/cobra/app/__init__.py", line 237, in <module>
    from app.controller import api
  File "/Users/x/cobra/app/controller/api.py", line 20, in <module>
    from engine import scan
  File "/Users/x/cobra/engine/scan.py", line 18, in <module>
    from utils import config, decompress
  File "/Users/x/cobra/utils/decompress.py", line 19, in <module>
    import magic
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/magic.py", line 171, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by lianfeng30** [comment]
brew install libmagic?
