### ISSUE TITLE
上传代码包时报错

### ISSUE THREAD

**Issue by popmedd** [wufeifei/cobra#471]
### System and Python Environment

Linux ubuntu 4.2.0-16-generic #19-Ubuntu
Python 2.7.10

上传代码包时报错
### Description
Traceback (most recent call last):
  File "/home/cobra/cobra/config.py", line 50, in __init__
    value = config.get(level1, level2)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'cobra'
[01:49:36] [CRITICAL] ./configs file configure failed.
Error: No section: 'cobra'
Traceback (most recent call last):
  File "/home/cobra/cobra/config.py", line 50, in __init__
    value = config.get(level1, level2)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'upload'
[01:49:50] [CRITICAL] ./configs file configure failed.
Error: No section: 'upload'

**Comment by wufeifei** [comment]
@popmedd 建议等月底正式版本上线后再使用。
