### ISSUE TITLE
svn扫描报错

### ISSUE THREAD

**Issue by kaisaint** [wufeifei/cobra#52]
./config file configure failed.
Error: No option 'upload_directory' in section: 'cobra'
See Help: https://github.com/wufeifei/cobra/wiki/Config
----------------------------------------
Exception happened during processing of request from ('192.168.1.100', 28605)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 183, in execute
    for data in application_iter:
  File "/usr/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 281, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/cobra/app/controller/api.py", line 73, in add_task
    code, result = scan.Scan(target).version(branch, new_version, old_version)
  File "/opt/cobra/engine/scan.py", line 76, in version
    repo_directory = os.path.join(config.Config('cobra', 'upload_directory').value, 'version/mogujie/')
  File "/opt/cobra/utils/config.py", line 31, in __init__
    exit()
  File "/usr/lib64/python2.7/site.py", line 364, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by wufeifei** [comment]
配置错误，按照这个重新配置下。
https://github.com/wufeifei/cobra/wiki/Config

**Comment by kaisaint** [comment]
[cobra]
#
# Domain
#
domain: cobra.wufeifei.com

#
# 0.0.0.0   can bind any domain
# 127.0.0.1 request localhost
#
host: 0.0.0.0

#
# default:80
#
port: 5000
debug: 0

logs_directory: logs

# NOTE: change it to a random string.(32\w)
secret_key: your_secret_key

[upload]
# upload src store path, default: uploads
# NOTE: no '/' or '\' at the end of the directory name.
directory: /tmp/cobra
extensions: .tar.gz|.rar|.zip
max_size: 200

#
# Database
#
[database]
mysql: mysql+mysqldb://root:xxxx@127.0.0.1:3306/cobra

#
# Subversion Account
#
[svn]
username:xxx
password:xxxxx

#
# Git Account
#
[git]
username:
password:


我的配置如上，不知道哪里有问题？

**Comment by wufeifei** [comment]
因为配置和代码不匹配 **更新下代码**
