### ISSUE TITLE
ImportError: No module named prettytable

### ISSUE THREAD

**Issue by wenqinruan** [wufeifei/cobra#544]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`|Darwin localhost 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64|
|Python|`python -V`|Python 2.7.10|
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]
Traceback (most recent call last):
  File "cobra.py", line 7, in <module>
    from cobra import main
  File "/usr/local/var/www/cobra/cobra/__init__.py", line 21, in <module>
    from . import cli, api, config
  File "/usr/local/var/www/cobra/cobra/cli.py", line 16, in <module>
    from .detection import Detection
  File "/usr/local/var/www/cobra/cobra/detection.py", line 15, in <module>
    from prettytable import PrettyTable
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prettytable.py", line 60, in <module>
    from cgi import escape
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cgi.py", line 50, in <module>
    import mimetools
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by wufeifei** [comment]
@wenqinruan 你电脑上应该有两个Python版本，将`./cobra.py`改成`python cobra.py`的方法使用。

**Comment by wufeifei** [comment]
为避免出现类似问题，已经将使用提示全部更改为`python cobra.py`

**Comment by wenqinruan** [comment]
最近在学习python，电脑上的python 版本比较混乱，
我是使用了/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so 替换了 /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so 解决的。
