### ISSUE TITLE
执行过程中报这个错误，

### ISSUE THREAD

**Issue by jozxing** [wufeifei/cobra#574]
Traceback (most recent call last):
  File "/home/xxxx/cobra/cobra/config.py", line 70, in __init__
    value = config.get(level1, level2)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'upload'
[CRITICAL] ./configs file configure failed.
Error: No section: 'upload'

**Comment by jozxing** [comment]
[WARNING] Traceback (most recent call last):
  File "/home/jove/cobra/cobra/__init__.py", line 82, in main
    cli.start(args.target, args.format, args.output, args.special_rules, a_sid)
  File "/home/jove/cobra/cobra/cli.py", line 65, in start
    target_mode = pa.target_mode
  File "/home/jove/cobra/cobra/utils.py", line 94, in target_mode
    if self.target.split('.')[-1] in Config('upload', 'extensions').value.split('|'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by wufeifei** [comment]
没有初始化配置文件，参考https://wufeifei.github.io/cobra/config
