### ISSUE TITLE
安装完抛这个异常

### ISSUE THREAD

**Issue by liang1981** [wufeifei/cobra#577]
Error processing line 1 of /usr/local/python/lib/python2.7/site-packages/phply-1.0.0-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/python/lib/python2.7/site.py", line 164, in addpackage
      exec line
    File "<string>", line 1, in <module>
  TypeError: module.__init__() argument 1 must be string, not unicode

Remainder of file ignored
Traceback (most recent call last):
  File "cobra.py", line 7, in <module>
    from cobra import main
  File "/data/sa/cobra/cobra/__init__.py", line 21, in <module>
    from . import cli, api, config
  File "/data/sa/cobra/cobra/cli.py", line 17, in <module>
    from .engine import scan, Running
  File "/data/sa/cobra/cobra/engine.py", line 28, in <module>
    from .parser import scan_parser
  File "/data/sa/cobra/cobra/parser.py", line 14, in <module>
    from phply.phplex import lexer  # 词法分析
ImportError: No module named phply.phplex

**Comment by wufeifei** [comment]
依赖没有安装全，尝试安装一下依赖
`pip install phply`

使用的时候
`python cobra.py -t test/`

**Comment by liang1981** [comment]
感谢 wufeifei如此快速的回复：）
是我这边pip源的问题，我从官网单独下载phply包安装没有问题，目前正在运行检测

**Comment by wufeifei** [comment]
@liang1981 

不客气，有问题随时Github上沟通。
