### ISSUE TITLE
扫描时报错

### ISSUE THREAD

**Issue by 0xfcryowbk2ca65z** [wufeifei/cobra#602]
机器是2G内存的虚拟机

[04:13:40] [INFO] [DETECTION] [FRAMEWORK] Unknown Framework
[04:13:40] [INFO] [CLI] [STATISTIC] Language: php Framework: Unknown Framework
[04:13:40] [INFO] [CLI] [STATISTIC] Files: 6669, Extensions:45, Consume: 3.361662
[04:13:41] [INFO] [PUSH] 17 CVE Rules
[04:14:38] [INFO] [PUSH] 76 Rules
[04:51:26] [WARNING] Traceback (most recent call last):
  File "/root/cobra/cobra/engine.py", line 634, in scan
    result = scan_parser(code_contents, rule_match, self.line_number, rule_repair)
  File "/root/cobra/cobra/parser.py", line 685, in scan_parser
    analysis(all_nodes, func, back_node, int(vul_lineno), function_params=None)
  File "/root/cobra/cobra/parser.py", line 650, in analysis
    analysis_if_else(node, back_node, vul_function, vul_lineo, function_params)
  File "/root/cobra/cobra/parser.py", line 470, in analysis_if_else
    analysis(node.node.nodes, vul_function, back_node, vul_lineno, function_params)
  File "/root/cobra/cobra/parser.py", line 650, in analysis
    analysis_if_else(node, back_node, vul_function, vul_lineo, function_params)
  File "/root/cobra/cobra/parser.py", line 470, in analysis_if_else
    analysis(node.node.nodes, vul_function, back_node, vul_lineno, function_params)
  File "/root/cobra/cobra/parser.py", line 637, in analysis
    analysis_echo_print(node, back_node, vul_function, vul_lineo, function_params)
  File "/root/cobra/cobra/parser.py", line 522, in analysis_echo_print
    analysis_binaryop_node(k_node, back_node, vul_function, vul_lineno, function_params)
  File "/root/cobra/cobra/parser.py", line 410, in analysis_binaryop_node
    params = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 140, in get_binaryop_params
    params_left = get_binaryop_deep_params(node.left, params)
  File "/root/cobra/cobra/parser.py", line 160, in get_binaryop_deep_params
    param = get_binaryop_params(node)
  File "/root/cobra/cobra/parser.py", line 144, in get_binaryop_params
    params = export_list(params, buffer_)
  File "/root/cobra/cobra/parser.py", line 43, in export_list
    export_params = export_list(param, export_params)
  File "/root/cobra/cobra/parser.py", line 46, in export_list
    export_params.append(param)
MemoryError

**Comment by wufeifei** [comment]
代码逻辑进入死循环导致内存占用过大
