### ISSUE TITLE
[AUTO] Unhandled exception (#b99fcc8c) Pickup Unicode

### ISSUE THREAD

**Issue by cobra-reporter** [wufeifei/cobra#609]
## Environment
```
Cobra version: 2.0.0-alpha.5
Python version: 2.7.12
Operating system: Linux-4.9.12-moby-x86_64-with-Ubuntu-16.04-xenial
Command line: cobra.py -t /tmp/web1
```
## Traceback
```
Traceback (most recent call last):
  File "/cobra/cobra/__init__.py", line 82, in main
    cli.start(args.target, args.format, args.output, args.special_rules, a_sid)
  File "/cobra/cobra/cli.py", line 75, in start
    files, file_count, time_consume = Directory(target_directory).collect_files()
  File "/cobra/cobra/pickup.py", line 163, in collect_files
    self.files(self.absolute_path)
  File "/cobra/cobra/pickup.py", line 206, in files
    self.files(directory, level + 1)
  File "/cobra/cobra/pickup.py", line 206, in files
    self.files(directory, level + 1)
  File "/cobra/cobra/pickup.py", line 206, in files
    self.files(directory, level + 1)
  File "/cobra/cobra/pickup.py", line 206, in files
    self.files(directory, level + 1)
  File "/cobra/cobra/pickup.py", line 205, in files
    if os.path.isdir(directory):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 36-38: ordinal not in range(128)

```

**Comment by wufeifei** [comment]
same as same #627
