### ISSUE TITLE
分析代码过程报错

### ISSUE THREAD

**Issue by alwaystest18** [wufeifei/cobra#66]
这个问题之前提过，当时回答的是不支持svn，改成git或upload，但实际上我就是用git和upload测试的，全部报这个错误，代码获取没有问题，是开始分析代码时出现了报错。
测试主机系统：ubuntu 14.04,Centos 6.5
安装过程是照着wiki来的，ubuntu的包名有些区别改了一下，centos原样安装的，中间未发生什么问题

`Traceback (most recent call last):
  File "/data/cobra/cobra.py", line 25, in <module>
    main()
  File "/data/cobra/cobra.py", line 21, in main
    manager.run()
  File "/usr/lib/python2.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/data/cobra/app/__init__.py", line 75, in run
    ['cloc', target], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
出现这个报错的结果就是马上就显示分析完成，查看报告的话就一直是统计代码行数中，过了一晚上再看报告出现了如下错误
`Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/cobra/app/controller/route.py", line 172, in report
    'files': common.convert_number(files),
  File "/data/cobra/utils/common.py", line 55, in convert_number
    return '{:20,}'.format(number)
ValueError: zero length field name in format`

**Comment by alwaystest18** [comment]
@wufeifei 测试了最新版本还是报错，跟以前一样，试了几个项目都是
`Traceback (most recent call last):
  File "/data/cobra-1.5/cobra.py", line 26, in <module>
    main()
  File "/data/cobra-1.5/cobra.py", line 22, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/data/cobra-1.5/app/__init__.py", line 76, in run
    ['cloc', target], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by wufeifei** [comment]
cloc没有装好
